version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: luxemart_db
      POSTGRES_USER: luxemart
      POSTGRES_PASSWORD: luxemart_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py seed_data &&
             gunicorn ecommerce.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - .:/app
      - media_files:/app/media
      - static_files:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://luxemart:luxemart_pass@db:5432/luxemart_db
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - media_files:/app/media
      - static_files:/app/staticfiles
    depends_on:
      - web

volumes:
  postgres_data:
  media_files:
  static_files:
